### ISSUE TITLE
Jasmine tests fail with Rails 7

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk_publishing_components#2621]
Jenkins deployment fails in Ruby 2.7. As a workaround we temporarily [pinned Rails to 6.x](https://github.com/alphagov/govuk_publishing_components/pull/2617) until further investigations on the issue are carried.

```
Puma starting in single mode...
* Puma version: 5.6.1 (ruby 2.7.5-p203) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: test
*          PID: 2468
* Listening on http://0.0.0.0:46281/
Use Ctrl-C to stop
Waiting for server on localhost:46281...
jasmine server started
Waiting for suite to finish in browser ...
rake aborted!
Selenium::WebDriver::Error::JavascriptError: javascript error: jsApiReporter is not defined
  (Session info: headless chrome=85.0.4183.83)
#0 0x5614ed894a39 <unknown>
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:305:in `execute_script'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:213:in `execute_script'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/jasmine_selenium_runner-3.0.0/lib/jasmine/runners/selenium.rb:32:in `finished?'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/jasmine_selenium_runner-3.0.0/lib/jasmine/runners/selenium.rb:49:in `wait_for_suites_to_finish_running'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/jasmine_selenium_runner-3.0.0/lib/jasmine/runners/selenium.rb:16:in `run'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/jasmine-3.10.0/lib/jasmine/ci_runner.rb:36:in `run'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/jasmine-3.10.0/lib/jasmine/tasks/jasmine.rake:55:in `block (2 levels) in <top (required)>'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/lib/rbenv/versions/2.7/bin/bundle:23:in `load'
/usr/lib/rbenv/versions/2.7/bin/bundle:23:in `<main>'
Tasks: TOP => default => app:jasmine:ci

**Comment by alex-ju** [comment]
Fixed in #2630 by switching to GitHub Actions

**Comment by ollietreend** [comment]
Following #2630, we can now successfully run the test suite on Ruby 2.7.

However, we're still unable to upgrade to Rails 7:

- Jasmine breaks in the same way as described above 😞
- RSpec and Rubocop tasks pass successfully

### Test results

Output produced by running:

```
bundle exec rake app:jasmine:ci
```

<details>
<summary>✅ Ruby 2.7 and Rails 6.1.4.6</summary>

```
$ bundle exec rake app:jasmine:ci
The Jasmine Ruby gems are deprecated. There will be no further releases after
the end of the Jasmine 3.x series. We recommend that most users migrate to the
jasmine-browser-runner npm package, which is the direct replacement for the
jasmine gem. See <https://jasmine.github.io/setup/browser.html> for setup
instructions, including for Rails applications that use either Sprockets or
Webpacker.

If jasmine-browser-runner doesn't meet your needs, one of these might:

* The jasmine npm package to run specs in Node.js:
  <https://github.com/jasmine/jasmine-npm>
* The standalone distribution to run specs in browsers with no additional
  tools: <https://github.com/jasmine/jasmine#installation>
* The jasmine-core npm package if all you need is the Jasmine assets:
  <https://github.com/jasmine/jasmine>. This is the direct equivalent of the
  jasmine-core Ruby gem.

To prevent this message from appearing, set the SUPPRESS_JASMINE_DEPRECATION
environment variable.

Waiting for server on localhost:50525...
Puma starting in single mode...
* Puma version: 5.6.2 (ruby 2.7.5-p203) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 25938
* Listening on http://0.0.0.0:50525
Use Ctrl-C to stop
Waiting for server on localhost:50525...
jasmine server started
Waiting for suite to finish in browser ...
............................................................................................................................................................................**....................................................................................................................................................................................................................................................................................................................................................................................................................................................
Pending:
        GOVUK.analyticsPlugins.error sends errors to Google Analytics
          Temporarily disabled with xit

        GOVUK.analyticsPlugins.error tracks only errors with a matching or blank filename
          Temporarily disabled with xit

610 specs, 0 failures, 2 pending specs
Randomized with seed 18685 (rake jasmine:ci[true,18685])
```

</details>

<details>
<summary>❌ Ruby 2.7 and Rails 7.0.2.2</summary>

```
$ bundle exec rake app:jasmine:ci
The Jasmine Ruby gems are deprecated. There will be no further releases after
the end of the Jasmine 3.x series. We recommend that most users migrate to the
jasmine-browser-runner npm package, which is the direct replacement for the
jasmine gem. See <https://jasmine.github.io/setup/browser.html> for setup
instructions, including for Rails applications that use either Sprockets or
Webpacker.

If jasmine-browser-runner doesn't meet your needs, one of these might:

* The jasmine npm package to run specs in Node.js:
  <https://github.com/jasmine/jasmine-npm>
* The standalone distribution to run specs in browsers with no additional
  tools: <https://github.com/jasmine/jasmine#installation>
* The jasmine-core npm package if all you need is the Jasmine assets:
  <https://github.com/jasmine/jasmine>. This is the direct equivalent of the
  jasmine-core Ruby gem.

To prevent this message from appearing, set the SUPPRESS_JASMINE_DEPRECATION
environment variable.

Puma starting in single mode...
* Puma version: 5.6.2 (ruby 2.7.5-p203) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 27405
* Listening on http://0.0.0.0:50662
Waiting for server on localhost:50662...
jasmine server started
Use Ctrl-C to stop
Waiting for suite to finish in browser ...
rake aborted!
Selenium::WebDriver::Error::JavascriptError: javascript error: jsApiReporter is not defined
  (Session info: headless chrome=98.0.4758.102)
0   chromedriver                        0x0000000108f2dee9 chromedriver + 5013225
1   chromedriver                        0x0000000108eb91d3 chromedriver + 4534739
2   chromedriver                        0x0000000108a8fa68 chromedriver + 170600
3   chromedriver                        0x0000000108a928b1 chromedriver + 182449
4   chromedriver                        0x0000000108a926d1 chromedriver + 181969
5   chromedriver                        0x0000000108a9326d chromedriver + 184941
6   chromedriver                        0x0000000108af4ce3 chromedriver + 584931
7   chromedriver                        0x0000000108ae17e2 chromedriver + 505826
8   chromedriver                        0x0000000108af4074 chromedriver + 581748
9   chromedriver                        0x0000000108ae16d3 chromedriver + 505555
10  chromedriver                        0x0000000108ab776e chromedriver + 333678
11  chromedriver                        0x0000000108ab8745 chromedriver + 337733
12  chromedriver                        0x0000000108ee9efe chromedriver + 4734718
13  chromedriver                        0x0000000108f03a19 chromedriver + 4839961
14  chromedriver                        0x0000000108f091c8 chromedriver + 4862408
15  chromedriver                        0x0000000108f043aa chromedriver + 4842410
16  chromedriver                        0x0000000108edea01 chromedriver + 4688385
17  chromedriver                        0x0000000108f1f538 chromedriver + 4953400
18  chromedriver                        0x0000000108f1f6c1 chromedriver + 4953793
19  chromedriver                        0x0000000108f35225 chromedriver + 5042725
20  libsystem_pthread.dylib             0x00007fff206838fc _pthread_start + 224
21  libsystem_pthread.dylib             0x00007fff2067f443 thread_start + 15
/Users/ollie/.rbenv/versions/2.7.5/bin/bundle:25:in `load'
/Users/ollie/.rbenv/versions/2.7.5/bin/bundle:25:in `<main>'
Tasks: TOP => app:jasmine:ci
(See full trace by running task with --trace)
```

</details>

### Changes to `Gemfile.lock`

Rails gems were updated by loosening the version constraint:

<details>
<summary>📝 Changes to <code>govuk_publishing_components.gemspec</code></summary>

```diff
   s.add_dependency "govuk_personalisation", ">= 0.7.0"
   s.add_dependency "kramdown"
   s.add_dependency "plek"
-  s.add_dependency "rails", ">= 6", "< 8"
+  s.add_dependency "rails", ">= 6"
   s.add_dependency "rouge"
   s.add_dependency "sprockets", "< 4"
```

</details>

And then running:

```
bundle update rails
```

<details>
<summary>▶️ Console output</summary>

```
$ bundle update rails
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using i18n 1.10.0
Using minitest 5.15.0
Using tzinfo 2.0.4
Using activesupport 7.0.2.2 (was 6.1.4.6)
Using builder 3.2.4
Using erubi 1.10.0
Using mini_portile2 2.8.0
Using racc 1.6.0
Using nokogiri 1.13.3 (x86_64-darwin)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.14.0
Using rails-html-sanitizer 1.4.2
Using actionview 7.0.2.2 (was 6.1.4.6)
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 7.0.2.2 (was 6.1.4.6)
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 7.0.2.2 (was 6.1.4.6)
Using globalid 1.0.0
Using activejob 7.0.2.2 (was 6.1.4.6)
Using activemodel 7.0.2.2 (was 6.1.4.6)
Using activerecord 7.0.2.2 (was 6.1.4.6)
Using marcel 1.0.2
Using mini_mime 1.1.2
Using activestorage 7.0.2.2 (was 6.1.4.6)
Using mail 2.7.1
Using digest 3.1.0
Using io-wait 0.2.1
Using timeout 0.2.0
Using net-protocol 0.1.2
Using strscan 3.0.1
Using net-imap 0.2.3
Using net-pop 0.1.1
Using net-smtp 0.3.1
Using actionmailbox 7.0.2.2 (was 6.1.4.6)
Using actionmailer 7.0.2.2 (was 6.1.4.6)
Using actiontext 7.0.2.2 (was 6.1.4.6)
Using public_suffix 4.0.6
Using addressable 2.8.0
Using ast 2.4.2
Using brakeman 5.2.1
Using bundler 1.17.3
Using byebug 11.1.3
Using matrix 0.4.2
Using regexp_parser 2.2.1
Using xpath 3.2.0
Using capybara 3.36.0
Using childprocess 3.0.0
Using coderay 1.1.3
Using rexml 3.2.5
Using crack 0.4.5
Using csv 3.2.2
Using diff-lcs 1.5.0
Using unf_ext 0.0.8
Using unf 0.1.4
Using domain_name 0.5.20190701
Using execjs 2.8.1
Using faker 2.19.0
Using faraday-net_http 2.0.1
Using ruby2_keywords 0.0.5
Using faraday 2.2.0
Using ffi 1.15.5
Using link_header 0.0.8
Using null_logger 0.0.1
Using plek 4.0.0
Using http-accept 1.7.0
Using http-cookie 1.0.4
Using mime-types-data 3.2022.0105
Using mime-types 3.4.1
Using netrc 0.11.0
Using rest-client 2.1.0
Using gds-api-adapters 79.0.0
Using request_store 1.5.1
Using logstasher 2.1.5
Using puma 5.6.2
Using method_source 1.0.0
Using thor 1.2.1
Using zeitwerk 2.5.4
Using railties 7.0.2.2 (was 6.1.4.6)
Using sentry-ruby-core 4.5.2
Using sentry-rails 4.5.2
Using sentry-ruby 4.5.2
Using statsd-ruby 1.5.0
Using kgio 2.11.4
Using raindrops 0.20.0
Using unicorn 5.8.0
Using govuk_app_config 4.3.0
Using rails 7.0.2.2 (was 6.1.4.6)
Using govuk_personalisation 0.11.2
Using kramdown 2.3.1
Using rouge 3.28.0
Using sprockets 3.7.2
Using govuk_publishing_components 28.6.0 from source at `.`
Using json-schema 2.8.1
Using govuk_schemas 4.3.0
Using rubyzip 2.3.2
Using selenium-webdriver 3.142.7
Using webdrivers 4.7.0
Using govuk_test 2.3.0
Using hashdiff 1.0.1
Using highline 2.0.3
Using i18n-coverage 0.2.0
Using parser 3.1.1.0
Using rails-i18n 7.0.2
Using rainbow 3.1.1
Using unicode-display_width 2.1.0
Using terminal-table 3.0.2
Using i18n-tasks 0.9.37
Using jasmine-core 3.10.1
Using phantomjs 2.1.1.0
Using webrick 1.7.0
Using jasmine 3.10.0
Using jasmine_selenium_runner 3.0.0
Using parallel 1.21.0
Using percy-capybara 5.0.0
Using pry 0.13.1
Using pry-byebug 3.9.0
Using rails_translation_manager 1.4.0
Using rspec-support 3.11.0
Using rspec-core 3.11.0
Using rspec-expectations 3.11.0
Using rspec-mocks 3.11.0
Using rspec-rails 5.1.0
Using rubocop-ast 1.15.1
Using ruby-progressbar 1.11.0
Using rubocop 1.25.0
Using rubocop-rails 2.13.2
Using rubocop-rake 0.6.0
Using rubocop-rspec 2.7.0
Using rubocop-govuk 4.3.0
Using sassc 2.4.0
Using sprockets-rails 3.4.2
Using tilt 2.0.10
Using sassc-rails 2.1.2
Using uglifier 4.2.0
Using webmock 3.8.3
Using yard 0.9.27
Bundle updated!
```

</details>

<details>
<summary>📝 Changes to <code>Gemfile.lock</code></summary>

```diff
 PATH
   remote: .
   specs:
     govuk_publishing_components (28.6.0)
       govuk_app_config
       govuk_personalisation (>= 0.7.0)
       kramdown
       plek
       rails (>= 6)
       rouge
       sprockets (< 4)
 
 GEM
   remote: https://rubygems.org/
   specs:
-    actioncable (6.1.4.6)
-      actionpack (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
+    actioncable (7.0.2.2)
+      actionpack (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
       nio4r (~> 2.0)
       websocket-driver (>= 0.6.1)
-    actionmailbox (6.1.4.6)
-      actionpack (= 6.1.4.6)
-      activejob (= 6.1.4.6)
-      activerecord (= 6.1.4.6)
-      activestorage (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
+    actionmailbox (7.0.2.2)
+      actionpack (= 7.0.2.2)
+      activejob (= 7.0.2.2)
+      activerecord (= 7.0.2.2)
+      activestorage (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
       mail (>= 2.7.1)
-    actionmailer (6.1.4.6)
-      actionpack (= 6.1.4.6)
-      actionview (= 6.1.4.6)
-      activejob (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
+      net-imap
+      net-pop
+      net-smtp
+    actionmailer (7.0.2.2)
+      actionpack (= 7.0.2.2)
+      actionview (= 7.0.2.2)
+      activejob (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
       mail (~> 2.5, >= 2.5.4)
+      net-imap
+      net-pop
+      net-smtp
       rails-dom-testing (~> 2.0)
-    actionpack (6.1.4.6)
-      actionview (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
-      rack (~> 2.0, >= 2.0.9)
+    actionpack (7.0.2.2)
+      actionview (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
+      rack (~> 2.0, >= 2.2.0)
       rack-test (>= 0.6.3)
       rails-dom-testing (~> 2.0)
       rails-html-sanitizer (~> 1.0, >= 1.2.0)
-    actiontext (6.1.4.6)
-      actionpack (= 6.1.4.6)
-      activerecord (= 6.1.4.6)
-      activestorage (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
+    actiontext (7.0.2.2)
+      actionpack (= 7.0.2.2)
+      activerecord (= 7.0.2.2)
+      activestorage (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
+      globalid (>= 0.6.0)
       nokogiri (>= 1.8.5)
-    actionview (6.1.4.6)
-      activesupport (= 6.1.4.6)
+    actionview (7.0.2.2)
+      activesupport (= 7.0.2.2)
       builder (~> 3.1)
       erubi (~> 1.4)
       rails-dom-testing (~> 2.0)
       rails-html-sanitizer (~> 1.1, >= 1.2.0)
-    activejob (6.1.4.6)
-      activesupport (= 6.1.4.6)
+    activejob (7.0.2.2)
+      activesupport (= 7.0.2.2)
       globalid (>= 0.3.6)
-    activemodel (6.1.4.6)
-      activesupport (= 6.1.4.6)
-    activerecord (6.1.4.6)
-      activemodel (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
-    activestorage (6.1.4.6)
-      actionpack (= 6.1.4.6)
-      activejob (= 6.1.4.6)
-      activerecord (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
-      marcel (~> 1.0.0)
+    activemodel (7.0.2.2)
+      activesupport (= 7.0.2.2)
+    activerecord (7.0.2.2)
+      activemodel (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
+    activestorage (7.0.2.2)
+      actionpack (= 7.0.2.2)
+      activejob (= 7.0.2.2)
+      activerecord (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
+      marcel (~> 1.0)
       mini_mime (>= 1.1.0)
-    activesupport (6.1.4.6)
+    activesupport (7.0.2.2)
       concurrent-ruby (~> 1.0, >= 1.0.2)
       i18n (>= 1.6, < 2)
       minitest (>= 5.1)
       tzinfo (~> 2.0)
-      zeitwerk (~> 2.3)
     addressable (2.8.0)
       public_suffix (>= 2.0.2, < 5.0)
     ast (2.4.2)
     brakeman (5.2.1)
     builder (3.2.4)
     byebug (11.1.3)
     capybara (3.36.0)
       addressable
       matrix
       mini_mime (>= 0.1.3)
       nokogiri (~> 1.8)
       rack (>= 1.6.0)
       rack-test (>= 0.6.3)
       regexp_parser (>= 1.5, < 3.0)
       xpath (~> 3.2)
     childprocess (3.0.0)
     coderay (1.1.3)
     concurrent-ruby (1.1.9)
     crack (0.4.5)
       rexml
     crass (1.0.6)
     csv (3.2.2)
     diff-lcs (1.5.0)
+    digest (3.1.0)
     domain_name (0.5.20190701)
       unf (>= 0.0.5, < 1.0.0)
     erubi (1.10.0)
     execjs (2.8.1)
     faker (2.19.0)
       i18n (>= 1.6, < 2)
     faraday (2.2.0)
       faraday-net_http (~> 2.0)
       ruby2_keywords (>= 0.0.4)
     faraday-net_http (2.0.1)
     ffi (1.15.5)
     gds-api-adapters (79.0.0)
       addressable
       link_header
       null_logger
       plek (>= 1.9.0)
       rest-client (~> 2.0)
     globalid (1.0.0)
       activesupport (>= 5.0)
     govuk_app_config (4.3.0)
       logstasher (>= 1.2.2, < 2.2.0)
       puma (~> 5.0)
       sentry-rails (~> 4.5.0)
       sentry-ruby (~> 4.5.0)
       statsd-ruby (~> 1.5.0)
       unicorn (>= 5.4, < 5.9)
     govuk_personalisation (0.11.2)
       plek (>= 1.9.0)
       rails (>= 6, < 8)
     govuk_schemas (4.3.0)
       json-schema (~> 2.8.0)
     govuk_test (2.3.0)
       brakeman (>= 5.0.2)
       capybara
       puma
       selenium-webdriver (>= 3.142)
       webdrivers (>= 4)
     hashdiff (1.0.1)
     highline (2.0.3)
     http-accept (1.7.0)
     http-cookie (1.0.4)
       domain_name (~> 0.5)
     i18n (1.10.0)
       concurrent-ruby (~> 1.0)
     i18n-coverage (0.2.0)
     i18n-tasks (0.9.37)
       activesupport (>= 4.0.2)
       ast (>= 2.1.0)
       erubi
       highline (>= 2.0.0)
       i18n
       parser (>= 2.2.3.0)
       rails-i18n
       rainbow (>= 2.2.2, < 4.0)
       terminal-table (>= 1.5.1)
+    io-wait (0.2.1)
     jasmine (3.10.0)
       jasmine-core (~> 3.10.0)
       phantomjs
       rack (>= 2.1.4)
       rake
       webrick
     jasmine-core (3.10.1)
     jasmine_selenium_runner (3.0.0)
       jasmine (~> 3.0)
       selenium-webdriver (~> 3.8)
     json-schema (2.8.1)
       addressable (>= 2.4)
     kgio (2.11.4)
     kramdown (2.3.1)
       rexml
     link_header (0.0.8)
     logstasher (2.1.5)
       activesupport (>= 5.2)
       request_store
     loofah (2.14.0)
       crass (~> 1.0.2)
       nokogiri (>= 1.5.9)
     mail (2.7.1)
       mini_mime (>= 0.1.1)
     marcel (1.0.2)
     matrix (0.4.2)
     method_source (1.0.0)
     mime-types (3.4.1)
       mime-types-data (~> 3.2015)
     mime-types-data (3.2022.0105)
     mini_mime (1.1.2)
     mini_portile2 (2.8.0)
     minitest (5.15.0)
+    net-imap (0.2.3)
+      digest
+      net-protocol
+      strscan
+    net-pop (0.1.1)
+      digest
+      net-protocol
+      timeout
+    net-protocol (0.1.2)
+      io-wait
+      timeout
+    net-smtp (0.3.1)
+      digest
+      net-protocol
+      timeout
     netrc (0.11.0)
     nio4r (2.5.8)
     nokogiri (1.13.3)
       mini_portile2 (~> 2.8.0)
       racc (~> 1.4)
     null_logger (0.0.1)
     parallel (1.21.0)
     parser (3.1.1.0)
       ast (~> 2.4.1)
     percy-capybara (5.0.0)
       capybara (>= 3)
     phantomjs (2.1.1.0)
     plek (4.0.0)
     pry (0.13.1)
       coderay (~> 1.1)
       method_source (~> 1.0)
     pry-byebug (3.9.0)
       byebug (~> 11.0)
       pry (~> 0.13.0)
     public_suffix (4.0.6)
     puma (5.6.2)
       nio4r (~> 2.0)
     racc (1.6.0)
     rack (2.2.3)
     rack-test (1.1.0)
       rack (>= 1.0, < 3)
-    rails (6.1.4.6)
-      actioncable (= 6.1.4.6)
-      actionmailbox (= 6.1.4.6)
-      actionmailer (= 6.1.4.6)
-      actionpack (= 6.1.4.6)
-      actiontext (= 6.1.4.6)
-      actionview (= 6.1.4.6)
-      activejob (= 6.1.4.6)
-      activemodel (= 6.1.4.6)
-      activerecord (= 6.1.4.6)
-      activestorage (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
+    rails (7.0.2.2)
+      actioncable (= 7.0.2.2)
+      actionmailbox (= 7.0.2.2)
+      actionmailer (= 7.0.2.2)
+      actionpack (= 7.0.2.2)
+      actiontext (= 7.0.2.2)
+      actionview (= 7.0.2.2)
+      activejob (= 7.0.2.2)
+      activemodel (= 7.0.2.2)
+      activerecord (= 7.0.2.2)
+      activestorage (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
       bundler (>= 1.15.0)
-      railties (= 6.1.4.6)
-      sprockets-rails (>= 2.0.0)
+      railties (= 7.0.2.2)
     rails-dom-testing (2.0.3)
       activesupport (>= 4.2.0)
       nokogiri (>= 1.6)
     rails-html-sanitizer (1.4.2)
       loofah (~> 2.3)
     rails-i18n (7.0.2)
       i18n (>= 0.7, < 2)
       railties (>= 6.0.0, < 8)
     rails_translation_manager (1.4.0)
       activesupport
       csv (~> 3.2)
       i18n-tasks
       rails-i18n
-    railties (6.1.4.6)
-      actionpack (= 6.1.4.6)
-      activesupport (= 6.1.4.6)
+    railties (7.0.2.2)
+      actionpack (= 7.0.2.2)
+      activesupport (= 7.0.2.2)
       method_source
-      rake (>= 0.13)
+      rake (>= 12.2)
       thor (~> 1.0)
+      zeitwerk (~> 2.5)
     rainbow (3.1.1)
     raindrops (0.20.0)
     rake (13.0.6)
     regexp_parser (2.2.1)
     request_store (1.5.1)
       rack (>= 1.4)
     rest-client (2.1.0)
       http-accept (>= 1.7.0, < 2.0)
       http-cookie (>= 1.0.2, < 2.0)
       mime-types (>= 1.16, < 4.0)
       netrc (~> 0.8)
     rexml (3.2.5)
     rouge (3.28.0)
     rspec-core (3.11.0)
       rspec-support (~> 3.11.0)
     rspec-expectations (3.11.0)
       diff-lcs (>= 1.2.0, < 2.0)
       rspec-support (~> 3.11.0)
     rspec-mocks (3.11.0)
       diff-lcs (>= 1.2.0, < 2.0)
       rspec-support (~> 3.11.0)
     rspec-rails (5.1.0)
       actionpack (>= 5.2)
       activesupport (>= 5.2)
       railties (>= 5.2)
       rspec-core (~> 3.10)
       rspec-expectations (~> 3.10)
       rspec-mocks (~> 3.10)
       rspec-support (~> 3.10)
     rspec-support (3.11.0)
     rubocop (1.25.0)
       parallel (~> 1.10)
       parser (>= 3.1.0.0)
       rainbow (>= 2.2.2, < 4.0)
       regexp_parser (>= 1.8, < 3.0)
       rexml
       rubocop-ast (>= 1.15.1, < 2.0)
       ruby-progressbar (~> 1.7)
       unicode-display_width (>= 1.4.0, < 3.0)
     rubocop-ast (1.15.1)
       parser (>= 3.0.1.1)
     rubocop-govuk (4.3.0)
       rubocop (= 1.25.0)
       rubocop-ast (= 1.15.1)
       rubocop-rails (= 2.13.2)
       rubocop-rake (= 0.6.0)
       rubocop-rspec (= 2.7.0)
     rubocop-rails (2.13.2)
       activesupport (>= 4.2.0)
       rack (>= 1.1)
       rubocop (>= 1.7.0, < 2.0)
     rubocop-rake (0.6.0)
       rubocop (~> 1.0)
     rubocop-rspec (2.7.0)
       rubocop (~> 1.19)
     ruby-progressbar (1.11.0)
     ruby2_keywords (0.0.5)
     rubyzip (2.3.2)
     sassc (2.4.0)
       ffi (~> 1.9)
     sassc-rails (2.1.2)
       railties (>= 4.0.0)
       sassc (>= 2.0)
       sprockets (> 3.0)
       sprockets-rails
       tilt
     selenium-webdriver (3.142.7)
       childprocess (>= 0.5, < 4.0)
       rubyzip (>= 1.2.2)
     sentry-rails (4.5.2)
       railties (>= 5.0)
       sentry-ruby-core (~> 4.5.0)
     sentry-ruby (4.5.2)
       concurrent-ruby (~> 1.0, >= 1.0.2)
       faraday (>= 1.0)
       sentry-ruby-core (= 4.5.2)
     sentry-ruby-core (4.5.2)
       concurrent-ruby
       faraday
     sprockets (3.7.2)
       concurrent-ruby (~> 1.0)
       rack (> 1, < 3)
     sprockets-rails (3.4.2)
       actionpack (>= 5.2)
       activesupport (>= 5.2)
       sprockets (>= 3.0.0)
     statsd-ruby (1.5.0)
+    strscan (3.0.1)
     terminal-table (3.0.2)
       unicode-display_width (>= 1.1.1, < 3)
     thor (1.2.1)
     tilt (2.0.10)
+    timeout (0.2.0)
     tzinfo (2.0.4)
       concurrent-ruby (~> 1.0)
     uglifier (4.2.0)
       execjs (>= 0.3.0, < 3)
     unf (0.1.4)
       unf_ext
     unf_ext (0.0.8)
     unicode-display_width (2.1.0)
     unicorn (5.8.0)
       kgio (~> 2.6)
       raindrops (~> 0.7)
     webdrivers (4.7.0)
       nokogiri (~> 1.6)
       rubyzip (>= 1.3.0)
       selenium-webdriver (> 3.141, < 5.0)
     webmock (3.8.3)
       addressable (>= 2.3.6)
       crack (>= 0.3.2)
       hashdiff (>= 0.4.0, < 2.0.0)
     webrick (1.7.0)
     websocket-driver (0.7.5)
       websocket-extensions (>= 0.1.0)
     websocket-extensions (0.1.5)
     xpath (3.2.0)
       nokogiri (~> 1.8)
     yard (0.9.27)
       webrick (~> 1.7.0)
     zeitwerk (2.5.4)
 
 PLATFORMS
   ruby
 
 DEPENDENCIES
   capybara (~> 3.25)
   faker (>= 2.11)
   gds-api-adapters
   govuk_publishing_components!
   govuk_schemas (~> 4.0)
   govuk_test (~> 2)
   i18n-coverage
   jasmine (~> 3.10.0)
   jasmine_selenium_runner (~> 3.0.0)
   percy-capybara (~> 5.0.0)
   pry-byebug
   rails_translation_manager
   rake
   rspec-rails (~> 5.0)
   rubocop-govuk
   sassc-rails (~> 2)
   uglifier (>= 4.1.0)
   webmock (~> 3.8.3)
   yard
 
 RUBY VERSION
    ruby 2.7.5p203
 
 BUNDLED WITH
    1.17.3
```

</details>

**Comment by ollietreend** [comment]
This was resolved in release [28.7.0](https://github.com/alphagov/govuk_publishing_components/blob/master/CHANGELOG.md#2870---yanked-due-to-missing-node-dependencies).
